function timemanager(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',uc='.cache.html',$='/',bc='0AAF8C45665BC0332A7B752DF582D0D6',cc='11AE99A3D0ED8A908D5CD57F026E9E89',dc='1D0FBF36D91FFD485E2851A69B8DEBAE',ec='20E7C137656649838F9ED7363B4A7AFC',fc='283970EE205F293B24C9D0BEECE48499',gc='3B11A67240657C74CB052B64A5C4AC92',hc='436EFD6EDBCD20F69EAEC49BFF950968',ic='4FCE33D1E4830B4D06B3D19B1E231A17',jc='50A4B9E0F78335C6F6176FA6E6A94B5F',kc='5506DDCC89B341E396FB7E1D2E6F14C1',lc='5D06F7F9D0AE3FED05CA79CC698B8698',mc='62AA3924F83586DA1DB3199E6A35BB36',nc='68C6661F3E5EE2D0D494B2C72D440F4B',oc='6C5BAFFA4FFD86D4328FB4078DDCADD0',pc='74276B3AFC7AE687E92007944D21A41C',qc='88370F839D1BA6C07E670C5D8B865C55',tc=':',nb='::',Cc='<script defer="defer">timemanager.onInjectionDone(\'timemanager\')<\/script>',gb='<script id="',qb='=',Z='?',Qb='ActiveXObject',sb='Bad handler "',Rb='ChromeTab.ChromeFrame',rc='D8276E511CBE6CA6AB16E29756195CE3',Bc='DOMContentLoaded',sc='F901FD7DD9E76D366EBB37F53E259AEC',ib='SCRIPT',fb='__gwt_marker_timemanager',Bb='android',Db='android_tablet',jb='base',bb='baseUrl',S='begin',Hb='blackberry',R='bootstrap',Pb='chromeframe',ab='clear.cache.gif',pb='content',Ib='desktop',X='end',Xb='gecko',Yb='gecko1_8',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',vc='gwt/standard/standard.css',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',Ac='head',_b='hosted.html?timemanager',zc='href',Wb='ie6',Vb='ie8',Ub='ie9',wb='iframe',_='img',Eb='ipad',Fb='iphone',xb="javascript:''",wc='link',$b='loadExternalRefs',kb='meta',Ab='mgwt.os',Cb='mobile',Jb='mobile.user.agent',Kb='mobilesafari',zb='moduleRequested',W='moduleStartup',Tb='msie',lb='name',Lb='not_mobile',Nb='opera',yb='position:absolute;width:0;height:0;border:none',xc='rel',Gb='retina',Sb='safari',cb='script',ac='selectingPermutation',Q='startup',yc='stylesheet',P='timemanager',db='timemanager.nocache.js',mb='timemanager::',eb='undefined',Zb='unknown',Mb='user.agent',Ob='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=O,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(P);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return G(a)}}timemanager=null;c.gwtOnLoad(y,P,s,x);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function C(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=E(bb);if(a!=null){return a}return O}
function h(){var a=m.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;m.write(gb+b+hb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=m.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
var k=g();if(k==O){k=h()}if(k==O){k=i()}if(k==O){k=j()}if(k==O){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=m.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(s+K)}}
v[Ab]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Bb)!=-1){if(a.indexOf(Cb)!=-1){return Bb}else{return Db}}if(a.indexOf(Eb)!=-1){return Eb}if(a.indexOf(Fb)!=-1){if(window.devicePixelRatio>=2){return Gb}return Fb}if(a.indexOf(Hb)!=-1){return Hb}return Ib}();return b}};u[Ab]={android:0,android_tablet:1,blackberry:2,desktop:3,ipad:4,iphone:5,retina:6};v[Jb]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Bb)!=-1){return Kb}if(a.indexOf(Fb)!=-1){return Kb}if(a.indexOf(Eb)!=-1){return Kb}if(a.indexOf(Hb)!=-1){return Lb}return Lb}();return b}};u[Jb]={mobilesafari:0,not_mobile:1};v[Mb]=function(){var c=navigator.userAgent.toLowerCase();var d=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return c.indexOf(Nb)!=-1}())return Nb;if(function(){return c.indexOf(Ob)!=-1||function(){if(c.indexOf(Pb)!=-1){return true}if(typeof window[Qb]!=eb){try{var b=new ActiveXObject(Rb);if(b){b.registerBhoIfNeeded();return true}}catch(a){}}return false}()}())return Sb;if(function(){return c.indexOf(Tb)!=-1&&m.documentMode>=9}())return Ub;if(function(){return c.indexOf(Tb)!=-1&&m.documentMode>=8}())return Vb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(c);if(a&&a.length==3)return d(a)>=6000}())return Wb;if(function(){return c.indexOf(Xb)!=-1}())return Yb;return Zb};u[Mb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};timemanager.onScriptLoad=function(){if(H){q=true;B()}};timemanager.onInjectionDone=function(){p=true;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:$b,millis:(new Date).getTime(),type:X});B()};D();C();var J;var K;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(P))){l.location.reload();return}K=_b;J=O}n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:ac});if(!A()){try{F([Hb,Lb,Sb],bc);F([Ib,Lb,Nb],cc);F([Bb,Lb,Sb],dc);F([Fb,Kb,Sb],ec);F([Ib,Lb,Yb],fc);F([Eb,Kb,Sb],gc);F([Ib,Lb,Ub],hc);F([Bb,Kb,Sb],ic);F([Gb,Kb,Sb],jc);F([Ib,Lb,Vb],kc);F([Ib,Kb,Sb],lc);F([Db,Kb,Sb],mc);F([Fb,Lb,Sb],nc);F([Hb,Kb,Sb],oc);F([Db,Lb,Sb],pc);F([Eb,Lb,Sb],qc);F([Gb,Lb,Sb],rc);F([Ib,Lb,Sb],sc);J=w[G(Ab)][G(Jb)][G(Mb)];var L=J.indexOf(tc);if(L!=-1){x=Number(J.substring(L+1));J=J.substring(0,L)}K=J+uc}catch(a){return}}var M;function N(){if(!r){r=true;if(!__gwt_stylesLoaded[vc]){var a=m.createElement(wc);__gwt_stylesLoaded[vc]=a;a.setAttribute(xc,yc);a.setAttribute(zc,s+vc);m.getElementsByTagName(Ac)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(Bc,N,false)}if(M){clearInterval(M)}}}
if(m.addEventListener){m.addEventListener(Bc,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(m.readyState)){I();N()}},50);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:$b,millis:(new Date).getTime(),type:S});m.write(Cc)}
timemanager();